# pigallery
---

- name: Reload Systemd
  listen: "reload systemd"
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart pigallery
  listen: "restart pigallery"
  ansible.builtin.systemd:
    name: "pigallery.service"
    state: "restarted"
  become: true
